export const ADDITION = "ADDITION"
export const SOUSTRACTION = "SOUSTRACTION"
export const MULTIPLICATION = "MULTIPLICATION"
export const NUMBER = "NUMBER"

export const BEGINWITHMULTIPLICATION = "BEGINWITHMULTIPLICATION"
export const MULTIPLEOPERATORS = "MULTIPLEOPERATORS"
export const NOERROR = ""

export const RESULT = "RESULT"
export const RESET = "RESET"